(function() {var implementors = {};
implementors["linfa"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"linfa/error/enum.Error.html\" title=\"enum linfa::error::Error\">Error</a>","synthetic":false,"types":["linfa::error::Error"]}];
implementors["linfa_bayes"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"linfa_bayes/enum.BayesError.html\" title=\"enum linfa_bayes::BayesError\">BayesError</a>","synthetic":false,"types":["linfa_bayes::error::BayesError"]}];
implementors["linfa_clustering"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"linfa_clustering/enum.GmmError.html\" title=\"enum linfa_clustering::GmmError\">GmmError</a>","synthetic":false,"types":["linfa_clustering::gaussian_mixture::errors::GmmError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"linfa_clustering/enum.KMeansError.html\" title=\"enum linfa_clustering::KMeansError\">KMeansError</a>","synthetic":false,"types":["linfa_clustering::k_means::errors::KMeansError"]}];
implementors["linfa_elasticnet"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"linfa_elasticnet/enum.Error.html\" title=\"enum linfa_elasticnet::Error\">Error</a>","synthetic":false,"types":["linfa_elasticnet::error::Error"]}];
implementors["linfa_ica"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"linfa_ica/error/enum.FastIcaError.html\" title=\"enum linfa_ica::error::FastIcaError\">FastIcaError</a>","synthetic":false,"types":["linfa_ica::error::FastIcaError"]}];
implementors["linfa_linear"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"linfa_linear/enum.LinearError.html\" title=\"enum linfa_linear::LinearError\">LinearError</a>","synthetic":false,"types":["linfa_linear::error::LinearError"]}];
implementors["linfa_pls"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"linfa_pls/enum.PlsError.html\" title=\"enum linfa_pls::PlsError\">PlsError</a>","synthetic":false,"types":["linfa_pls::errors::PlsError"]}];
implementors["linfa_svm"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"linfa_svm/error/enum.SvmResult.html\" title=\"enum linfa_svm::error::SvmResult\">SvmResult</a>","synthetic":false,"types":["linfa_svm::error::SvmResult"]}];
implementors["linfa_tsne"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"linfa_tsne/enum.TSneError.html\" title=\"enum linfa_tsne::TSneError\">TSneError</a>","synthetic":false,"types":["linfa_tsne::error::TSneError"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()