var N = null;var sourcesIndex = {};
sourcesIndex["linfa"] = {"name":"","dirs":[{"name":"dataset","files":["impl_dataset.rs","impl_records.rs","impl_targets.rs","iter.rs","mod.rs","multi_target_model.rs"]}],"files":["correlation.rs","error.rs","lib.rs","metrics_classification.rs","metrics_clustering.rs","metrics_regression.rs","prelude.rs","traits.rs"]};
sourcesIndex["linfa_bayes"] = {"name":"","files":["error.rs","gaussian_nb.rs","lib.rs"]};
sourcesIndex["linfa_clustering"] = {"name":"","dirs":[{"name":"appx_dbscan","dirs":[{"name":"cells_grid","files":["cell.rs","mod.rs"]},{"name":"clustering","files":["mod.rs"]},{"name":"counting_tree","files":["mod.rs"]}],"files":["algorithm.rs","hyperparameters.rs","mod.rs"]},{"name":"dbscan","files":["algorithm.rs","hyperparameters.rs","mod.rs"]},{"name":"gaussian_mixture","files":["algorithm.rs","errors.rs","hyperparameters.rs","mod.rs"]},{"name":"k_means","files":["algorithm.rs","errors.rs","hyperparameters.rs","init.rs","mod.rs"]}],"files":["lib.rs","utils.rs"]};
sourcesIndex["linfa_datasets"] = {"name":"","files":["lib.rs"]};
sourcesIndex["linfa_elasticnet"] = {"name":"","files":["algorithm.rs","error.rs","hyperparameters.rs","lib.rs"]};
sourcesIndex["linfa_hierarchical"] = {"name":"","files":["lib.rs"]};
sourcesIndex["linfa_ica"] = {"name":"","files":["error.rs","fast_ica.rs","lib.rs"]};
sourcesIndex["linfa_kernel"] = {"name":"","files":["inner.rs","lib.rs","sparse.rs"]};
sourcesIndex["linfa_linear"] = {"name":"","dirs":[{"name":"glm","files":["distribution.rs","link.rs"]}],"files":["error.rs","float.rs","glm.rs","lib.rs","ols.rs"]};
sourcesIndex["linfa_logistic"] = {"name":"","files":["argmin_param.rs","float.rs","lib.rs"]};
sourcesIndex["linfa_pls"] = {"name":"","files":["errors.rs","lib.rs","pls_generic.rs","pls_svd.rs","utils.rs"]};
sourcesIndex["linfa_reduction"] = {"name":"","dirs":[{"name":"diffusion_map","files":["algorithms.rs","hyperparameters.rs","mod.rs"]}],"files":["lib.rs","pca.rs","utils.rs"]};
sourcesIndex["linfa_svm"] = {"name":"","files":["classification.rs","error.rs","lib.rs","permutable_kernel.rs","regression.rs","solver_smo.rs"]};
sourcesIndex["linfa_trees"] = {"name":"","dirs":[{"name":"decision_trees","files":["algorithm.rs","hyperparameters.rs","iter.rs","mod.rs","tikz.rs"]}],"files":["lib.rs"]};
sourcesIndex["linfa_tsne"] = {"name":"","files":["error.rs","lib.rs"]};
createSourceSidebar();
